ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address VARCHAR(500);

CREATE TABLE IF NOT EXISTS user_attributes (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    attr_key VARCHAR(120) NOT NULL,
    attr_value VARCHAR(1000),
    CONSTRAINT fk_attr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_attr UNIQUE (user_id, attr_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
